export enum AgentSettings {
    PROJECT_ID = 'project_id',
    CLIENT_EMAIL = 'client_email',
    AGENT_ID = 'agent_id',
    AGENT_REGION = 'agent_region',
    AGENT_DEFAULT_LANGUAGE = 'agent_default_language',
    ENVIRONMENT_ID = 'environment_id',
    PRIVATE_KEY = 'private_key',
    AGENT_VERSION = 'agent_version',
    FALLBACK_RESPONSES_LIMIT = 'fallback_responses_limit',
    FALLBACK_TARGET_DEPARTMENT = 'fallback_target_department',
    HANDOVER_MESSAGE = 'handover_message',
    UNABLE_TO_HANDOVER = 'no_agents_for_handover_message',
    SERVICE_UNAVAILABLE_MESSAGE = 'service_unavailable_message',
    CLOSE_CHAT_MESSAGE = 'close_chat_message',
    HIDE_QUICK_REPLIES = 'hide_quickreplies',
    ENABLE_CHAT_CLOSED_BY_VISITOR = 'enable_chat_closed_by_visitor_event',
    CHAT_CLOSED_BY_VISITOR_EVENT = 'chat_closed_by_visitor_event',
    ENABLE_WELCOME_MESSAGE = 'enable_welcome_message',
    WELCOME_MESSAGE = 'welcome_message',
    WELCOME_INTENT_ON_START = 'welcome_intent_on_start',
    ENABLE_CUSTOMER_TIMEOUT = 'enable_customer_timeout',
    CUSTOMER_TIMEOUT_TIME = 'customer_timeout_time',
    CUSTOMER_TIMEOUT_WARNING_TIME = 'customer_timeout_warning_time',
    CUSTOMER_TIMEOUT_WARNING_MESSAGE = 'customer_timeout_warning_message',
    SESSION_MAINTENANCE_INTERVAL = 'session_maintenance_interval',
    SESSION_MAINTENANCE_EVENT_NAME = 'session_maintenance_event_name',
}
